apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/horatiualex/pillmate
    newName: ghcr.io/horatiualex/pillmate
    newTag: latest
