apiVersion: apps/v1
kind: Deployment
metadata:
  name: pillmate-deployment
  labels:
    app: pillmate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pillmate
  template:
    metadata:
      labels:
        app: pillmate
    spec:
      containers:
      - name: pillmate
        image: ghcr.io/raducosminalexandru/pillmate:v6
        ports:
        - containerPort: 3000
