apiVersion: v1
kind: Service
metadata:
  name: pillmate-service
spec:
  selector:
    app: pillmate
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000 
      nodePort: 30080 
  type: NodePort
